// Code generated by cmd/reset; DO NOT EDIT.

package resetexample

func (s *Stats) Reset() {
	if s == nil {
		return
	}

	s.Count = 0
	s.Name = ""
	s.Active = false
	s.Values = s.Values[:0]
	clear(s.Labels)
	s.Rate = 0
	if s.NamePtr != nil {
		*s.NamePtr = ""
	}
	if s.child != nil {
		if resetter, ok := interface{}(s.child).(interface{ Reset() }); ok {
			resetter.Reset()
		} else {
			*s.child = Stats{}
		}
	}
}
