FROM golang:1.26-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .

ARG BUILD_VERSION=N/A
ARG BUILD_DATE=N/A
ARG BUILD_COMMIT=N/A

RUN CGO_ENABLED=0 go build -trimpath \
    -ldflags="-s -w -X main.buildVersion=${BUILD_VERSION} -X main.buildDate=${BUILD_DATE} -X main.buildCommit=${BUILD_COMMIT}" \
    -o /server ./cmd/server

FROM alpine:3.20
COPY --from=builder /server /server
CMD ["/server"]
