name: yandex-metrics

services:
  postgres:
    image: postgres:16-alpine
    container_name: metrics-postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: ..
      dockerfile: deployments/Dockerfile.server
    container_name: metrics-server
    ports:
      - "8080:8080"
      - "6060:6060"
    environment:
      ADDRESS: 0.0.0.0:8080
      DATABASE_DSN: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      FILE_STORAGE_PATH: /data/metrics.json
      STORE_INTERVAL: "300"
      RESTORE: "true"
      KEY: ${KEY:-}
      AUDIT_FILE: ${AUDIT_FILE:-}
      AUDIT_URL: ${AUDIT_URL:-}
      PPROF_ADDRESS: 0.0.0.0:6060
    volumes:
      - server_data:/data
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  agent:
    build:
      context: ..
      dockerfile: deployments/Dockerfile.agent
    container_name: metrics-agent
    ports:
     - "6061:6061"
    environment:
      PPROF_ADDRESS: 0.0.0.0:6061
      ADDRESS: server:8080
      REPORT_INTERVAL: "10"
      POLL_INTERVAL: "2"
      KEY: ${KEY:-}
      RATE_LIMIT: ${RATE_LIMIT:-5}
    depends_on:
      - server
    restart: unless-stopped

volumes:
  postgres_data:
  server_data:
