// Утилита reset для кодогенерации методов Reset() у структур,
// помеченных комментарием `// generate:reset`.
//
// Утилита сканирует все Go-пакеты начиная с текущего модуля, находит
// структуры с маркером и генерирует файл reset.gen.go в каждом пакете,
// содержащем такие структуры.
//
// # Запуск
//
//	go run ./cmd/reset
//
// # Правила генерации Reset()
//
//   - Примитивы сбрасываются к zero value
//   - Slice обрезаются: s = s[:0]
//   - Map очищаются: clear(m)
//   - Указатели: если не nil, значение под указателем сбрасывается
//   - Вложенные структуры/указатели проверяются через interface{ Reset() }
package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/token"
	"go/types"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"

	"golang.org/x/tools/go/packages"
)

// resetTmpl — шаблон для генерации метода Reset().
var resetTmpl = template.Must(template.New("reset").Parse(`// Code generated by cmd/reset; DO NOT EDIT.

package {{.Package}}
{{range .Structs}}
func ({{.Recv}} *{{.Name}}) Reset() {
	if {{.Recv}} == nil {
		return
	}
{{range .Fields}}
{{.Code}}{{end}}
}
{{end}}
`))

// templateData — входные данные для шаблона.
type templateData struct {
	Package string
	Structs []structTmplData
}

type structTmplData struct {
	Name   string
	Recv   string
	Fields []fieldTmplData
}

type fieldTmplData struct {
	Code string
}

func main() {
	cfg := &packages.Config{
		Mode: packages.NeedName |
			packages.NeedFiles |
			packages.NeedSyntax |
			packages.NeedTypes |
			packages.NeedTypesInfo |
			packages.NeedCompiledGoFiles,
		Dir: ".",
	}

	pkgs, err := packages.Load(cfg, "./...")
	if err != nil {
		log.Fatalf("failed to load packages: %v", err)
	}

	for _, pkg := range pkgs {
		if len(pkg.Errors) > 0 {
			continue
		}
		generateForPackage(pkg)
	}
}

// structInfo хранит информацию о структуре для генерации.
type structInfo struct {
	name       string
	structType *types.Struct
}

// generateForPackage ищет структуры с маркером и генерирует reset.gen.go.
func generateForPackage(pkg *packages.Package) {
	var structs []structInfo

	for _, file := range pkg.Syntax {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			if hasResetMarker(genDecl.Doc) {
				for _, spec := range genDecl.Specs {
					ts := spec.(*ast.TypeSpec)
					if si, ok := extractStruct(pkg, ts); ok {
						structs = append(structs, si)
					}
				}
				continue
			}

			// Для сгруппированных type (...) — проверяем каждый TypeSpec.
			for _, spec := range genDecl.Specs {
				ts := spec.(*ast.TypeSpec)
				if hasResetMarker(ts.Doc) || hasResetMarker(ts.Comment) {
					if si, ok := extractStruct(pkg, ts); ok {
						structs = append(structs, si)
					}
				}
			}
		}
	}

	if len(structs) == 0 {
		return
	}

	// Определяем директорию пакета.
	var dir string
	if len(pkg.CompiledGoFiles) > 0 {
		dir = filepath.Dir(pkg.CompiledGoFiles[0])
	} else if len(pkg.GoFiles) > 0 {
		dir = filepath.Dir(pkg.GoFiles[0])
	} else {
		return
	}

	// Подготавливаем данные для шаблона.
	data := templateData{Package: pkg.Name}
	for _, si := range structs {
		data.Structs = append(data.Structs, buildStructData(si))
	}

	var buf bytes.Buffer
	if err := resetTmpl.Execute(&buf, data); err != nil {
		log.Fatalf("failed to execute template for %s: %v", pkg.PkgPath, err)
	}

	outPath := filepath.Join(dir, "reset.gen.go")
	formatted, err := format.Source(buf.Bytes())
	if err != nil {
		log.Printf("warning: failed to format generated code for %s: %v", pkg.PkgPath, err)
		formatted = buf.Bytes()
	}

	if err := os.WriteFile(outPath, formatted, 0644); err != nil {
		log.Fatalf("failed to write %s: %v", outPath, err)
	}

	fmt.Printf("generated: %s (%d structs)\n", outPath, len(structs))
}

func hasResetMarker(cg *ast.CommentGroup) bool {
	if cg == nil {
		return false
	}
	for _, c := range cg.List {
		if strings.TrimSpace(strings.TrimPrefix(c.Text, "//")) == "generate:reset" {
			return true
		}
	}
	return false
}

func extractStruct(pkg *packages.Package, ts *ast.TypeSpec) (structInfo, bool) {
	obj := pkg.TypesInfo.Defs[ts.Name]
	if obj == nil {
		return structInfo{}, false
	}
	named, ok := obj.Type().(*types.Named)
	if !ok {
		return structInfo{}, false
	}
	st, ok := named.Underlying().(*types.Struct)
	if !ok {
		return structInfo{}, false
	}
	return structInfo{name: ts.Name.Name, structType: st}, true
}

// buildStructData формирует данные для шаблона из structInfo.
func buildStructData(si structInfo) structTmplData {
	recv := strings.ToLower(si.name[:1])
	st := si.structType

	var fields []fieldTmplData
	for i := 0; i < st.NumFields(); i++ {
		field := st.Field(i)
		access := recv + "." + field.Name()
		code := fieldResetCode(access, field.Type())
		if code != "" {
			fields = append(fields, fieldTmplData{Code: code})
		}
	}

	return structTmplData{
		Name:   si.name,
		Recv:   recv,
		Fields: fields,
	}
}

// fieldResetCode генерирует строку кода для сброса одного поля.
func fieldResetCode(access string, fieldType types.Type) string {
	switch t := fieldType.Underlying().(type) {
	case *types.Basic:
		return fmt.Sprintf("\t%s = %s", access, zeroForBasic(t))

	case *types.Slice:
		return fmt.Sprintf("\t%s = %s[:0]", access, access)

	case *types.Map:
		return fmt.Sprintf("\tclear(%s)", access)

	case *types.Pointer:
		return pointerResetCode(access, t.Elem())

	case *types.Struct:
		return structResetCode(access, fieldType)

	default:
		// Интерфейсы, каналы, функции.
		return fmt.Sprintf("\t%s = nil", access)
	}
}

func pointerResetCode(access string, elemType types.Type) string {
	var buf bytes.Buffer
	_, _ = fmt.Fprintf(&buf, "\tif %s != nil {\n", access)

	switch elemType.Underlying().(type) {
	case *types.Basic:
		basic := elemType.Underlying().(*types.Basic)
		_, _ = fmt.Fprintf(&buf, "\t\t*%s = %s\n", access, zeroForBasic(basic))

	case *types.Slice:
		_, _ = fmt.Fprintf(&buf, "\t\t*%s = (*%s)[:0]\n", access, access)

	case *types.Map:
		_, _ = fmt.Fprintf(&buf, "\t\tclear(*%s)\n", access)

	case *types.Struct:
		// Runtime type assertion — как в примере из задания.
		_, _ = fmt.Fprintf(&buf, "\t\tif resetter, ok := interface{}(%s).(interface{ Reset() }); ok {\n", access)
		_, _ = fmt.Fprintf(&buf, "\t\t\tresetter.Reset()\n")
		_, _ = fmt.Fprintf(&buf, "\t\t} else {\n")
		_, _ = fmt.Fprintf(&buf, "\t\t\t*%s = %s{}\n", access, typeName(elemType))
		_, _ = fmt.Fprintf(&buf, "\t\t}\n")

	default:
		_, _ = fmt.Fprintf(&buf, "\t\t*%s = nil\n", access)
	}

	_, _ = fmt.Fprintf(&buf, "\t}")
	return buf.String()
}

func structResetCode(access string, fieldType types.Type) string {
	var buf bytes.Buffer
	_, _ = fmt.Fprintf(&buf, "\tif resetter, ok := interface{}(&%s).(interface{ Reset() }); ok {\n", access)
	_, _ = fmt.Fprintf(&buf, "\t\tresetter.Reset()\n")
	_, _ = fmt.Fprintf(&buf, "\t} else {\n")
	_, _ = fmt.Fprintf(&buf, "\t\t%s = %s{}\n", access, typeName(fieldType))
	_, _ = fmt.Fprintf(&buf, "\t}")
	return buf.String()
}

func zeroForBasic(t *types.Basic) string {
	switch {
	case t.Info()&types.IsBoolean != 0:
		return "false"
	case t.Info()&types.IsInteger != 0:
		return "0"
	case t.Info()&types.IsFloat != 0:
		return "0"
	case t.Info()&types.IsComplex != 0:
		return "0"
	case t.Info()&types.IsString != 0:
		return `""`
	default:
		return "0"
	}
}

func typeName(t types.Type) string {
	if named, ok := t.(*types.Named); ok {
		return named.Obj().Name()
	}
	return t.String()
}
