syntax = "proto3";

package metrics;

option go_package = "github.com/aikowocki/yandex-go-musthave-metrics/pkg/proto";

message Metric {
  string id = 1;

  enum MType {
    UNSPECIFIED = 0; // дефолт для отлова когда не передели значение
    GAUGE = 1;
    COUNTER = 2;
  }

  MType type = 2;
  
  // oneof гарантирует что будет заполнено одно поле из
  // nil = клиент не передал значение 
  oneof payload {
      double value = 4;
      int64 delta = 3;
  }
}

message UpdateMetricsRequest {
  repeated Metric metrics = 1;
}

message UpdateMetricsResponse {}

service Metrics {
  rpc UpdateMetrics(UpdateMetricsRequest) returns (UpdateMetricsResponse);
}
